version: '3.8'

services:
  app:
    container_name: wankuldex-app
    build:
      context: .
      target: production
    restart: always
    env_file: .env.local
    volumes:
      - .:/app
    ports:
      - "54111:3000"
    working_dir: /app

