version: '3.8'

services:
  app:
    container_name: wankuldex-app
    build:
      context: .
      target: production
    restart: always
    command: yarn dev
    env_file: .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "54111:3000"